//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mj.compiler.resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("mj.compiler.resources.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string expressionStatement {
            get {
                return ResourceManager.GetString("expressionStatement", resourceCulture);
            }
        }
        
        internal static string intLiteratTooBig {
            get {
                return ResourceManager.GetString("intLiteratTooBig", resourceCulture);
            }
        }
        
        internal static string floatLiteratTooBig {
            get {
                return ResourceManager.GetString("floatLiteratTooBig", resourceCulture);
            }
        }
        
        internal static string duplicateMethodName {
            get {
                return ResourceManager.GetString("duplicateMethodName", resourceCulture);
            }
        }
        
        internal static string duplicateClassName {
            get {
                return ResourceManager.GetString("duplicateClassName", resourceCulture);
            }
        }
        
        internal static string duplicateParamName {
            get {
                return ResourceManager.GetString("duplicateParamName", resourceCulture);
            }
        }
        
        internal static string duplicateVar {
            get {
                return ResourceManager.GetString("duplicateVar", resourceCulture);
            }
        }
        
        internal static string varParamNameConflict {
            get {
                return ResourceManager.GetString("varParamNameConflict", resourceCulture);
            }
        }
        
        internal static string mainMethodNotDefined {
            get {
                return ResourceManager.GetString("mainMethodNotDefined", resourceCulture);
            }
        }
        
        internal static string mainMethodSig {
            get {
                return ResourceManager.GetString("mainMethodSig", resourceCulture);
            }
        }
        
        internal static string ifConditonType {
            get {
                return ResourceManager.GetString("ifConditonType", resourceCulture);
            }
        }
        
        internal static string forConditonType {
            get {
                return ResourceManager.GetString("forConditonType", resourceCulture);
            }
        }
        
        internal static string whileConditonType {
            get {
                return ResourceManager.GetString("whileConditonType", resourceCulture);
            }
        }
        
        internal static string doWhileConditonType {
            get {
                return ResourceManager.GetString("doWhileConditonType", resourceCulture);
            }
        }
        
        internal static string switchSelectorType {
            get {
                return ResourceManager.GetString("switchSelectorType", resourceCulture);
            }
        }
        
        internal static string methodNotDefined {
            get {
                return ResourceManager.GetString("methodNotDefined", resourceCulture);
            }
        }
        
        internal static string wrongNumberOfArgs {
            get {
                return ResourceManager.GetString("wrongNumberOfArgs", resourceCulture);
            }
        }
        
        internal static string varInitTypeMismatch {
            get {
                return ResourceManager.GetString("varInitTypeMismatch", resourceCulture);
            }
        }
        
        internal static string paramTypeMismatch {
            get {
                return ResourceManager.GetString("paramTypeMismatch", resourceCulture);
            }
        }
        
        internal static string caseExpressionType {
            get {
                return ResourceManager.GetString("caseExpressionType", resourceCulture);
            }
        }
        
        internal static string duplicateCaseLabels {
            get {
                return ResourceManager.GetString("duplicateCaseLabels", resourceCulture);
            }
        }
        
        internal static string undefinedVariable {
            get {
                return ResourceManager.GetString("undefinedVariable", resourceCulture);
            }
        }
        
        internal static string undefinedType {
            get {
                return ResourceManager.GetString("undefinedType", resourceCulture);
            }
        }
        
        internal static string undefinedAspect {
            get {
                return ResourceManager.GetString("undefinedAspect", resourceCulture);
            }
        }
        
        internal static string returnVoidMethod {
            get {
                return ResourceManager.GetString("returnVoidMethod", resourceCulture);
            }
        }
        
        internal static string returnNonVoidMethod {
            get {
                return ResourceManager.GetString("returnNonVoidMethod", resourceCulture);
            }
        }
        
        internal static string returnTypeMismatch {
            get {
                return ResourceManager.GetString("returnTypeMismatch", resourceCulture);
            }
        }
        
        internal static string conditionalBoolean {
            get {
                return ResourceManager.GetString("conditionalBoolean", resourceCulture);
            }
        }
        
        internal static string conditionalMismatch {
            get {
                return ResourceManager.GetString("conditionalMismatch", resourceCulture);
            }
        }
        
        internal static string continueNotInLoop {
            get {
                return ResourceManager.GetString("continueNotInLoop", resourceCulture);
            }
        }
        
        internal static string breakNotInLoopSwitch {
            get {
                return ResourceManager.GetString("breakNotInLoopSwitch", resourceCulture);
            }
        }
        
        internal static string assignmentLHS {
            get {
                return ResourceManager.GetString("assignmentLHS", resourceCulture);
            }
        }
        
        internal static string assignmentUncompatible {
            get {
                return ResourceManager.GetString("assignmentUncompatible", resourceCulture);
            }
        }
        
        internal static string incDecArgument {
            get {
                return ResourceManager.GetString("incDecArgument", resourceCulture);
            }
        }
        
        internal static string unresolvedUnaryOperator {
            get {
                return ResourceManager.GetString("unresolvedUnaryOperator", resourceCulture);
            }
        }
        
        internal static string unresolvedBinaryOperator {
            get {
                return ResourceManager.GetString("unresolvedBinaryOperator", resourceCulture);
            }
        }
        
        internal static string missingReturnStatement {
            get {
                return ResourceManager.GetString("missingReturnStatement", resourceCulture);
            }
        }
        
        internal static string unreachableCodeDetected {
            get {
                return ResourceManager.GetString("unreachableCodeDetected", resourceCulture);
            }
        }
        
        internal static string unassignedVariable {
            get {
                return ResourceManager.GetString("unassignedVariable", resourceCulture);
            }
        }
        
        internal static string multipleDefaults {
            get {
                return ResourceManager.GetString("multipleDefaults", resourceCulture);
            }
        }
        
        internal static string selectOnPrimitive {
            get {
                return ResourceManager.GetString("selectOnPrimitive", resourceCulture);
            }
        }
        
        internal static string unknownField {
            get {
                return ResourceManager.GetString("unknownField", resourceCulture);
            }
        }
        
        internal static string undefinedClass {
            get {
                return ResourceManager.GetString("undefinedClass", resourceCulture);
            }
        }
    }
}
